### ISSUE TITLE
GitHub link gives 404 Error

### ISSUE THREAD

**Issue by lisamarie616** [learn-co-curriculum/sinatra-from-scratch-readme#4]
The GitHub link for this lab returns a 404 Error

**Comment by AnnJohn** [comment]
Hi @lisamarie616 sorry about that. We'll look into this and let you know here when it's been fixed. Thanks!

**Comment by lisamarie616** [comment]
Ok, thank you!!

**Comment by AnnJohn** [comment]
hi @lisamarie616 this should be fixed now. thanks and sorry for the trouble.
