### ISSUE TITLE
Clone this respository?

### ISSUE THREAD

**Issue by jcpny1** [learn-co-curriculum/sinatra-from-scratch-readme#8]
"This is not a lab, as there's nothing for you to submit. But to follow along with the lesson, make sure you fork and clone this repository."
I was able to find a repository called 'sinatra-from-scratch-readme-demo-000', but it would be nice if a link was provided.

**Comment by maxwellbenton** [comment]
Hello,

Thank you for your feedback on this repository.  We have reviewed the readme and added a link to make it easier to access the repo and follow along.

Maxwell Benton
Learn Curriculum Team
