### ISSUE TITLE
Perhaps define what middleware means?

### ISSUE THREAD

**Issue by michaelwahlin** [learn-co-curriculum/sinatra-from-scratch-readme#9]
The text is as follows.  I could be wrong, but I don't remember the term middleware being defined previously.

> Sinatra relies on Rack for its middleware.

**Comment by maxwellbenton** [comment]
Hello Michael,

Thank you for your feedback.  We've taken a look at the repo and added a sentence to clarify what middleware is.

Maxwell Benton
Learn Curriculum Team
